name: mvp
headers:
  X-MACHINE-ID: test2
latency: !Constant 1400
rules:
  - matches: POST /my-route/test
    status: 200/text
    body: "{test: 2}"
  - matches: PATCH /other-route/:name/:test
    latency: !Constant 1000
    status: 400/text
    body: testsè