namespace: bloom-perf
app: mochi

replicaCount: 1

image:
  repository: ghcr.io/bloom-perf/mochi
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: initial-release-2@sha256:bd4c4c5ccb71398a349139cf7555d949fe3352e8e594cec62e5121261bd24856
containerPort: 3000
service:
  type: ClusterIP
  port: 9090
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  paths:
    - path: /mochi(/|$)(.*)

nameOverride: ""
fullnameOverride: ""

configName: mochi-config
volumes:
  - name: mochi-config-volume
    mountPath: /var/config
    configMap:
      name: mochi-config
      defaultMode: 777
env:
  - name: CONFIG_PATH
    value: /var/config
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

restartPolicy: Never
ttlSecondsAfterFinished: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: {}

affinity: {}
